### ISSUE TITLE
ReadFrom blocking forever

### ISSUE THREAD

**Issue by lufia** [surgebase/netx#2]
I'm trying to fix broken tests on https://github.com/lufia/netx/commit/b3dd21060ba651e448113eb2eb126e662d4ddecb

netx package calls rconn.ReadFrom at Pinger.receiver().
[https://github.com/surge/netx/blob/master/ping.go#L410]
And rconn is closed at Pinger.Stop() via deferred function in Pinger.receiver().

I think, rconn.ReadFrom is blocked forever when return an error from rconn.WriteTo.

Can I set to deadline?

**Comment by zhenjl** [comment]
Hi @lufia did you fix this with the merges you sent? thx!
