### ISSUE TITLE
Error: it is broken with the latest "golang.org/x/net/icmp" package.

### ISSUE THREAD

**Issue by kobeld** [surgebase/netx#3]
Hi, I am trying to test the surgemq [pingmq](https://github.com/surgemq/surgemq/tree/master/examples/pingmq) example, which importing this package. But It doesn't work because this package is broken.

My Go version is 1.5 and can see the error by running the test.

```
$ go test  
# github.com/surge/netx
./ping.go:632: not enough arguments in call to m.Body.Len
./ping.go:654: not enough arguments in call to m.Body.Len
FAIL    github.com/surge/netx [build failed]
```

It seems like it's using the outdated `icmp` package. The latest version needs to pass the IP protocol param to the Len method. You can check the detail [here](https://github.com/golang/net/blob/master/icmp/messagebody.go#L11).

**Comment by zhenjl** [comment]
Fixed by @lufia's fix
